spring:
  application:
    name: weather
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/weather}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    change-log: classpath:db/changelog/changelog-root.xml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate